Homework/todo
AliceZlygosteva/ReactCreative pull request #7
Opened 2022-01-11 00:39 UTC by AliceZlygosteva

2022-01-11 10:43 UTC, BubbaCat requested changes
Все очень хорошо и легко читается, мне нравится :)

2022-01-11 10:43 UTC, BubbaCat commented on react_crt/src/components/Header/Header.module.scss
>  .header {
Лучше писать css стили в от в таком порядке
1.Сначала положение элемента относительно других
2. Затем размеры и отступы
3.Рамка border, она частично относится к размерам
4.Общее оформление содержимого
5.Цветовое и стилевое оформление

так легче читать и расширять, но это просто заметка на будущее, можно поставить npm пакет, которые это будет делать за нас в одном команду

2022-01-11 10:43 UTC, BubbaCat commented on react_crt/src/components/ToDoList/ToDoList.js
> +        return arrTasks.filter((task) => !!task.isCompleted);
task.isCompleted

2022-01-11 10:43 UTC, BubbaCat commented on react_crt/src/components/ToDoList/ToDoList.js
> +            item={item}
можно <ItemToDo {...this.props}  вместо всего этого/> 
и раз мы не передаем children, то можно закрыть сразу

2022-01-11 10:43 UTC, BubbaCat commented on react_crt/src/containers/ToDoContainer/ToDoContainer.js
> +    const listFromStorage = JSON.parse(localStorage.getItem("todoList")) || [];
По хорошему вот это вынести в отдельный сервис который получает и преобразовывает данные, т.к сейчас у нас компонент очень сильно зациклен на этой реализации, а у нас должна быть возможность легко менять место получения данных. Про это мы поговорим в ближайших лекциях

2022-01-11 10:43 UTC, BubbaCat commented on react_crt/src/containers/ToDoContainer/ToDoContainer.js
> +          list={list}
{...this.state}

2022-01-11 10:58 UTC, BubbaCat commented on react_crt/src/containers/ToDoContainer/ToDoContainer.js
> +    const { list } = this.state;
т.к при добавлении мы основываемся на пред. состоянии, то лучше использовать функцию как параметр setState
(prevState) => ....

2022-01-11 11:07 UTC, BubbaCat commented on react_crt/src/components/ItemToDo/ItemToDo.js
> +const TASKS_TYPE = {
Лучше вынести в отдельный файл

2022-01-12 11:20 UTC, AliceZlygosteva commented on react_crt/src/containers/ToDoContainer/ToDoContainer.js
> +          list={list}
Если я пропишу {  ...this.state }, то поле isShow тоже будет передано в ToDoList. А мы его там не используем. Это ок?

2022-01-12 11:46 UTC, AliceZlygosteva commented on react_crt/src/containers/ToDoContainer/ToDoContainer.js
> +    const { list } = this.state;
Не совсем поняла коммент. Я понимаю, что могу передать первым аргументом в setState функцию и вытащить старые пропсы. Но setState задачи и сохранение её в локал сторейдж происходит в отдельной функции saveList, т.к. используется это действие в нескольких методах. Можно чуть-чуть подробнее?

2022-01-19 09:56 UTC, merged